export const START_LOADING = "TOGGLE_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
export const GET_RATES = "GET_RATES";
export const GET_COMPARE_RATES = "GET_COMPARE_RATES";
export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const SET_CURRENT_COMPARE_DATE = "SET_CURRENT_COMPARE_DATE";
